BF-FrontEnd-class/agile-development-group2-loruki-rebuild

- .cspell.json
- README.md
> update project definition 

- index.html
- package.json
- planning/development-strategy.md
- styles/something.css
> add devstrategy

- index.html
- styles/something.css
> add navigation

- index.html
- styles/something.css
- styles/utilities.css
> add form and utilities.css

- pages/docs-page.html
> add navigaton to docs.html

- .cspell.json
- index.html
- styles/something.css
> add Container2

- index.html
- styles/something.css
> update title of the homepage

- index.html
- styles/something.css
> add description

- index.html
- styles/something.css
> add cloud to the homepage

- pages/docs-page.html
> add footer to docs page

- pages/features-page.html
> add features page logo

- pages/features-page.html
> add features navigation

- pages/docs-page.html
- styles/something.css
> add introduction

- pages/features-page.html
> add container grid to the features page

- pages/features-page.html
> add footer to features page

- pages/features-page.html
> add social media to footer features page

- pages/features-page.html
> add first image to features page

- pages/features-page.html
> add second image to features page

- pages/features-page.html
> remove names to social media features page

- pages/features-page.html
- planning/retrospective.md
> add retrospective
